Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Lovely");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("Thought I found a way");
Console.WriteLine("Thought I found a way out (found)");
Console.WriteLine("you never go away (never go away)");
Console.WriteLine("So I guess I gotta stay now");
Console.WriteLine("");
Console.WriteLine("OhI hope some day I'll make it out of here");
Console.WriteLine("Even if it takes all night or a hundred years");
Console.WriteLine("Need a place to hide, but I can't find one near");
Console.WriteLine("Wanna feel alive, outside I can't fight my fear");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Isn't it lovely, all alone");
Console.WriteLine("Heart made of glass, my mind of stone");
Console.WriteLine("Tear me to pieces, skin to bone");
Console.WriteLine("Hello, welcome home");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("Walkin' out of town");
Console.WriteLine("Lookin' for a better place (lookin' for a better place)");
Console.WriteLine("Something's on my mind (mind)");
Console.WriteLine("Always in my head space");
Console.WriteLine("But I know some day I'll make it out of here");
Console.WriteLine("Even if it takes all night or a hundred years");
Console.WriteLine("Need a place to hide, but I can't find one near");
Console.WriteLine("Wanna feel alive, outside I can't fight my fear");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Isn't it lovely, all alone");
Console.WriteLine("Heart made of glass, my mind of stone");
Console.WriteLine("Tear me to pieces, skin to boneHello, welcome home");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("Whoa, yeah");
Console.WriteLine("Yeah, ah");
Console.WriteLine("Whoa, whoa");
Console.WriteLine("Hello, welcome home");
